

[theme]
backgroundColor = '#5a8956'


secondaryBackgroundColor = 'hsl(153, 37%, 12%)'

textColor = '#ffffff'
primaryColor = 'rgb(73, 166, 246)'
theme.borderColor= '#0a1709'

font = "sans serif"
baseFontSize = 12

#0acfcf'